{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "POC for API Documentation",
    "description": "POC for API Doc Design and Collaboration"
  },
  "servers": [
    {
      "url": "https://localhost:9292"
    },
    {
      "url": "https://qa.goshd.com"
    }
  ],
  "tags": [
    {
      "name": "Examples"
    },
    {
      "name": "Charts"
    }
  ],
  "paths": {
    "/api/meta/charts": {
      "get": {
        "summary": "Get all charts",
        "operationId": "getAllCharts",
        "tags": [
          "Charts"
        ],
        "responses": {
          "200": {
            "description": "Get all available charts from system",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "name": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "display_name": {
                        "type": "string"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "content_type": {
                        "type": "string"
                      },
                      "poll_frequency": {
                        "type": "string"
                      },
                      "data_directory": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "recent_editions": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "edition_name": {
                              "type": "string"
                            },
                            "updated_at": {
                              "type": "string",
                              "format": "date-time"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unknown error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "description": "Common error response object schema",
                    "properties": {
                      "error_type": {
                        "description": "A type of error",
                        "type": "string"
                      },
                      "user_message": {
                        "description": "A human readable error message",
                        "type": "string"
                      },
                      "error_code": {
                        "description": "A error code associated to error",
                        "type": "string"
                      }
                    }
                  },
                  "example": {
                    "error": {
                      "error_type": "InternalError",
                      "user_message": "Unable to connect",
                      "error_code": "500"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/meta/charts/{chartId}/edition": {
      "get": {
        "summary": "Get most recent edition of chart",
        "operationId": "getMostRecentChartEdition",
        "tags": [
          "Charts"
        ],
        "parameters": [
          {
            "name": "chartId",
            "description": "The unique identifier of the example entity",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "The unique identifier of the example entity",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Get most recent chart edition",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "chart_name": {
                      "type": "string"
                    },
                    "chart_display_name": {
                      "type": "string"
                    },
                    "chart_content_type": {
                      "type": "string"
                    },
                    "chart_edition": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "updated_at": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "data": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "entity_id": {
                                "type": "string"
                              },
                              "rank": {
                                "type": "integer"
                              },
                              "brand_data": {
                                "type": "object",
                                "properties": {
                                  "id": {
                                    "type": "string"
                                  },
                                  "canonical_name": {
                                    "type": "string"
                                  },
                                  "slug": {
                                    "type": "string"
                                  },
                                  "created_at": {
                                    "type": "string",
                                    "format": "date-time"
                                  },
                                  "updated_at": {
                                    "type": "string",
                                    "format": "date-time"
                                  },
                                  "departments": {
                                    "type": "array",
                                    "items": {
                                      "type": "string"
                                    }
                                  },
                                  "brand_clusters": {
                                    "type": "array",
                                    "items": {
                                      "type": "string"
                                    }
                                  },
                                  "cover_shot": {
                                    "type": "object",
                                    "properties": {
                                      "id": {
                                        "type": "string"
                                      },
                                      "picture": {
                                        "type": "string"
                                      },
                                      "path": {
                                        "type": "string"
                                      },
                                      "path_small": {
                                        "type": "string"
                                      },
                                      "path_thumb": {
                                        "type": "string"
                                      },
                                      "url": {
                                        "type": "string"
                                      },
                                      "url_small": {
                                        "type": "string"
                                      },
                                      "url_thumb": {
                                        "type": "string"
                                      },
                                      "content_type": {
                                        "type": "string"
                                      },
                                      "created_at": {
                                        "type": "string",
                                        "format": "date-time"
                                      }
                                    }
                                  },
                                  "logo": {
                                    "type": "object",
                                    "properties": {
                                      "id": {
                                        "type": "string"
                                      },
                                      "picture": {
                                        "type": "string"
                                      },
                                      "path": {
                                        "type": "string"
                                      },
                                      "path_small": {
                                        "type": "string"
                                      },
                                      "path_thumb": {
                                        "type": "string"
                                      },
                                      "url": {
                                        "type": "string"
                                      },
                                      "url_small": {
                                        "type": "string"
                                      },
                                      "url_thumb": {
                                        "type": "string"
                                      },
                                      "content_type": {
                                        "type": "string"
                                      },
                                      "created_at": {
                                        "type": "string",
                                        "format": "date-time"
                                      }
                                    }
                                  },
                                  "aliases": {
                                    "type": "array",
                                    "items": {
                                      "type": "string"
                                    }
                                  },
                                  "alias_slugs": {
                                    "type": "array",
                                    "items": {
                                      "type": "string"
                                    }
                                  },
                                  "descriptions": {
                                    "type": "object",
                                    "additionalProperties": {
                                      "type": "object",
                                      "properties": {
                                        "top_description": {
                                          "type": "string"
                                        },
                                        "more_description": {
                                          "type": "string"
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Unknown error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "description": "Common error response object schema",
                    "properties": {
                      "error_type": {
                        "description": "A type of error",
                        "type": "string"
                      },
                      "user_message": {
                        "description": "A human readable error message",
                        "type": "string"
                      },
                      "error_code": {
                        "description": "A error code associated to error",
                        "type": "string"
                      }
                    }
                  },
                  "example": {
                    "error": {
                      "error_type": "InternalError",
                      "user_message": "Unable to connect",
                      "error_code": "500"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/emaples": {
      "get": {
        "summary": "Get all examples from system",
        "operationId": "getAllExamples",
        "tags": [
          "Examples"
        ],
        "responses": {
          "200": {
            "description": "Get all examples",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "name": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "display_name": {
                        "type": "string"
                      },
                      "tags": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "content_type": {
                        "type": "string"
                      },
                      "poll_frequency": {
                        "type": "string"
                      },
                      "data_directory": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "recent_editions": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "description": "example nested object",
                          "properties": {
                            "edition_name": {
                              "type": "string"
                            },
                            "updated_at": {
                              "type": "string",
                              "format": "date-time"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No example found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Unknown error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create new example",
        "operationId": "postExample",
        "tags": [
          "Examples"
        ],
        "responses": {
          "201": {
            "description": "Get all example entities",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "display_name": {
                      "type": "string"
                    },
                    "tags": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "content_type": {
                      "type": "string"
                    },
                    "poll_frequency": {
                      "type": "string"
                    },
                    "data_directory": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "recent_editions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "description": "example nested object",
                        "properties": {
                          "edition_name": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "date-time"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No example found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Unknown error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/emaples/{exampleId}": {
      "get": {
        "summary": "Get example by id",
        "operationId": "getExamplesById",
        "tags": [
          "Examples"
        ],
        "parameters": [
          {
            "name": "exampleId",
            "description": "The unique identifier of the example entity",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "The unique identifier of the example entity",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Get all example from system",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "display_name": {
                      "type": "string"
                    },
                    "tags": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "content_type": {
                      "type": "string"
                    },
                    "poll_frequency": {
                      "type": "string"
                    },
                    "data_directory": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "recent_editions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "description": "example nested object",
                        "properties": {
                          "edition_name": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "date-time"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No example found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Unknown error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "description": "Common error response object schema",
                  "properties": {
                    "error_type": {
                      "description": "A type of error",
                      "type": "string"
                    },
                    "user_message": {
                      "description": "A human readable error message",
                      "type": "string"
                    },
                    "error_code": {
                      "description": "A error code associated to error",
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "ChartId": {
        "name": "exampleId",
        "description": "The unique identifier of the example entity",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "description": "The unique identifier of the example entity",
          "format": "uuid"
        }
      }
    },
    "schemas": {
      "Error": {
        "type": "object",
        "description": "Common error response object schema",
        "properties": {
          "error_type": {
            "description": "A type of error",
            "type": "string"
          },
          "user_message": {
            "description": "A human readable error message",
            "type": "string"
          },
          "error_code": {
            "description": "A error code associated to error",
            "type": "string"
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "description": "Common error response object schema",
          "properties": {
            "error_type": {
              "description": "A type of error",
              "type": "string"
            },
            "user_message": {
              "description": "A human readable error message",
              "type": "string"
            },
            "error_code": {
              "description": "A error code associated to error",
              "type": "string"
            }
          }
        },
        "example": {
          "error": {
            "error_type": "InternalError",
            "user_message": "Unable to connect",
            "error_code": "500"
          }
        }
      },
      "ExampleId": {
        "type": "string",
        "description": "The unique identifier of a chart",
        "format": "uuid"
      },
      "Example": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "display_name": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "content_type": {
            "type": "string"
          },
          "poll_frequency": {
            "type": "string"
          },
          "data_directory": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "recent_editions": {
            "type": "array",
            "items": {
              "type": "object",
              "description": "example nested object",
              "properties": {
                "edition_name": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            }
          }
        }
      },
      "NestedExample": {
        "type": "object",
        "description": "example nested object",
        "properties": {
          "edition_name": {
            "type": "string"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "Chart": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "display_name": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "content_type": {
            "type": "string"
          },
          "poll_frequency": {
            "type": "string"
          },
          "data_directory": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "recent_editions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "edition_name": {
                  "type": "string"
                },
                "updated_at": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            }
          }
        }
      },
      "MostRecentChartEdition": {
        "type": "object",
        "properties": {
          "chart_name": {
            "type": "string"
          },
          "chart_display_name": {
            "type": "string"
          },
          "chart_content_type": {
            "type": "string"
          },
          "chart_edition": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "created_at": {
                "type": "string",
                "format": "date-time"
              },
              "updated_at": {
                "type": "string",
                "format": "date-time"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "entity_id": {
                      "type": "string"
                    },
                    "rank": {
                      "type": "integer"
                    },
                    "brand_data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "canonical_name": {
                          "type": "string"
                        },
                        "slug": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "updated_at": {
                          "type": "string",
                          "format": "date-time"
                        },
                        "departments": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "brand_clusters": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "cover_shot": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "picture": {
                              "type": "string"
                            },
                            "path": {
                              "type": "string"
                            },
                            "path_small": {
                              "type": "string"
                            },
                            "path_thumb": {
                              "type": "string"
                            },
                            "url": {
                              "type": "string"
                            },
                            "url_small": {
                              "type": "string"
                            },
                            "url_thumb": {
                              "type": "string"
                            },
                            "content_type": {
                              "type": "string"
                            },
                            "created_at": {
                              "type": "string",
                              "format": "date-time"
                            }
                          }
                        },
                        "logo": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "picture": {
                              "type": "string"
                            },
                            "path": {
                              "type": "string"
                            },
                            "path_small": {
                              "type": "string"
                            },
                            "path_thumb": {
                              "type": "string"
                            },
                            "url": {
                              "type": "string"
                            },
                            "url_small": {
                              "type": "string"
                            },
                            "url_thumb": {
                              "type": "string"
                            },
                            "content_type": {
                              "type": "string"
                            },
                            "created_at": {
                              "type": "string",
                              "format": "date-time"
                            }
                          }
                        },
                        "aliases": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "alias_slugs": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "descriptions": {
                          "type": "object",
                          "additionalProperties": {
                            "type": "object",
                            "properties": {
                              "top_description": {
                                "type": "string"
                              },
                              "more_description": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "X_HTTP_AUTHORIZATION"
      },
      "PartnerKey": {
        "type": "apiKey",
        "in": "header",
        "name": "X_PM_PARTNER_KEY"
      }
    }
  },
  "security": [
    {
      "ApiKey": []
    },
    {
      "PartnerKey": []
    }
  ]
}